/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum CashFlowType
{
  DIVIDEND = 0,
  INTEREST_ON_OWN_CAPITAL = 1,
  DEPOSIT = 2,
  WITHDRAWAL = 3,
}
