/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class TableCellTypes : TBase
{
  private string _text;
  private string _markdown;
  private double _percent;
  private double _currency;
  private double _number;
  private double _percentage_point;

  public string Text
  {
    get
    {
      return _text;
    }
    set
    {
      __isset.text = true;
      this._text = value;
    }
  }

  /// <summary>
  /// Criado na versão 0.8.1.
  /// </summary>
  public string Markdown
  {
    get
    {
      return _markdown;
    }
    set
    {
      __isset.markdown = true;
      this._markdown = value;
    }
  }

  public double Percent
  {
    get
    {
      return _percent;
    }
    set
    {
      __isset.percent = true;
      this._percent = value;
    }
  }

  public double Currency
  {
    get
    {
      return _currency;
    }
    set
    {
      __isset.currency = true;
      this._currency = value;
    }
  }

  public double Number
  {
    get
    {
      return _number;
    }
    set
    {
      __isset.number = true;
      this._number = value;
    }
  }

  public double Percentage_point
  {
    get
    {
      return _percentage_point;
    }
    set
    {
      __isset.percentage_point = true;
      this._percentage_point = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool text;
    public bool markdown;
    public bool percent;
    public bool currency;
    public bool number;
    public bool percentage_point;
  }

  public TableCellTypes() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Text = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              Markdown = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Double) {
              Percent = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Double) {
              Currency = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Double) {
              Number = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Double) {
              Percentage_point = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("TableCellTypes");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Text != null && __isset.text) {
        field.Name = "text";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Text);
        oprot.WriteFieldEnd();
      }
      if (__isset.percent) {
        field.Name = "percent";
        field.Type = TType.Double;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Percent);
        oprot.WriteFieldEnd();
      }
      if (__isset.currency) {
        field.Name = "currency";
        field.Type = TType.Double;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Currency);
        oprot.WriteFieldEnd();
      }
      if (__isset.number) {
        field.Name = "number";
        field.Type = TType.Double;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Number);
        oprot.WriteFieldEnd();
      }
      if (__isset.percentage_point) {
        field.Name = "percentage_point";
        field.Type = TType.Double;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Percentage_point);
        oprot.WriteFieldEnd();
      }
      if (Markdown != null && __isset.markdown) {
        field.Name = "markdown";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Markdown);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("TableCellTypes(");
    bool __first = true;
    if (Text != null && __isset.text) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Text: ");
      __sb.Append(Text);
    }
    if (Markdown != null && __isset.markdown) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Markdown: ");
      __sb.Append(Markdown);
    }
    if (__isset.percent) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Percent: ");
      __sb.Append(Percent);
    }
    if (__isset.currency) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Currency: ");
      __sb.Append(Currency);
    }
    if (__isset.number) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Number: ");
      __sb.Append(Number);
    }
    if (__isset.percentage_point) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Percentage_point: ");
      __sb.Append(Percentage_point);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

