/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class Transaction : TBase
{
  private StockBuyTransaction _stock_buy;
  private StockSellTransaction _stock_sell;
  private StockLendingTransaction _stock_lending;
  private StockLendingReturningTransaction _stock_lending_returning;

  public StockBuyTransaction Stock_buy
  {
    get
    {
      return _stock_buy;
    }
    set
    {
      __isset.stock_buy = true;
      this._stock_buy = value;
    }
  }

  public StockSellTransaction Stock_sell
  {
    get
    {
      return _stock_sell;
    }
    set
    {
      __isset.stock_sell = true;
      this._stock_sell = value;
    }
  }

  public StockLendingTransaction Stock_lending
  {
    get
    {
      return _stock_lending;
    }
    set
    {
      __isset.stock_lending = true;
      this._stock_lending = value;
    }
  }

  public StockLendingReturningTransaction Stock_lending_returning
  {
    get
    {
      return _stock_lending_returning;
    }
    set
    {
      __isset.stock_lending_returning = true;
      this._stock_lending_returning = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool stock_buy;
    public bool stock_sell;
    public bool stock_lending;
    public bool stock_lending_returning;
  }

  public Transaction() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Stock_buy = new StockBuyTransaction();
              Stock_buy.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Stock_sell = new StockSellTransaction();
              Stock_sell.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              Stock_lending = new StockLendingTransaction();
              Stock_lending.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Struct) {
              Stock_lending_returning = new StockLendingReturningTransaction();
              Stock_lending_returning.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("Transaction");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Stock_buy != null && __isset.stock_buy) {
        field.Name = "stock_buy";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Stock_buy.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Stock_sell != null && __isset.stock_sell) {
        field.Name = "stock_sell";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Stock_sell.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Stock_lending != null && __isset.stock_lending) {
        field.Name = "stock_lending";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        Stock_lending.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Stock_lending_returning != null && __isset.stock_lending_returning) {
        field.Name = "stock_lending_returning";
        field.Type = TType.Struct;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        Stock_lending_returning.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("Transaction(");
    bool __first = true;
    if (Stock_buy != null && __isset.stock_buy) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Stock_buy: ");
      __sb.Append(Stock_buy== null ? "<null>" : Stock_buy.ToString());
    }
    if (Stock_sell != null && __isset.stock_sell) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Stock_sell: ");
      __sb.Append(Stock_sell== null ? "<null>" : Stock_sell.ToString());
    }
    if (Stock_lending != null && __isset.stock_lending) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Stock_lending: ");
      __sb.Append(Stock_lending== null ? "<null>" : Stock_lending.ToString());
    }
    if (Stock_lending_returning != null && __isset.stock_lending_returning) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Stock_lending_returning: ");
      __sb.Append(Stock_lending_returning== null ? "<null>" : Stock_lending_returning.ToString());
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

