//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var transaction_ttypes = require('./transaction_types');


var ttypes = require('./transaction_file_importer_types');
//HELPER FUNCTIONS AND STRUCTURES

var TransactionFileImporter_extract_args = function(args) {
  this.data = null;
  if (args) {
    if (args.data !== undefined && args.data !== null) {
      this.data = args.data;
    }
  }
};
TransactionFileImporter_extract_args.prototype = {};
TransactionFileImporter_extract_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.data = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TransactionFileImporter_extract_args.prototype.write = function(output) {
  output.writeStructBegin('TransactionFileImporter_extract_args');
  if (this.data !== null && this.data !== undefined) {
    output.writeFieldBegin('data', Thrift.Type.STRING, 1);
    output.writeString(this.data);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TransactionFileImporter_extract_result = function(args) {
  this.success = null;
  this.col_quantity_error = null;
  if (args instanceof ttypes.WrongFileStructure) {
    this.col_quantity_error = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [transaction_ttypes.Transaction]);
    }
    if (args.col_quantity_error !== undefined && args.col_quantity_error !== null) {
      this.col_quantity_error = args.col_quantity_error;
    }
  }
};
TransactionFileImporter_extract_result.prototype = {};
TransactionFileImporter_extract_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new transaction_ttypes.Transaction();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.col_quantity_error = new ttypes.WrongFileStructure();
        this.col_quantity_error.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TransactionFileImporter_extract_result.prototype.write = function(output) {
  output.writeStructBegin('TransactionFileImporter_extract_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.col_quantity_error !== null && this.col_quantity_error !== undefined) {
    output.writeFieldBegin('col_quantity_error', Thrift.Type.STRUCT, 1);
    this.col_quantity_error.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TransactionFileImporterClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
TransactionFileImporterClient.prototype = {};
TransactionFileImporterClient.prototype.seqid = function() { return this._seqid; };
TransactionFileImporterClient.prototype.new_seqid = function() { return this._seqid += 1; };
TransactionFileImporterClient.prototype.extract = function(data, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_extract(data);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_extract(data);
  }
};

TransactionFileImporterClient.prototype.send_extract = function(data) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('extract', Thrift.MessageType.CALL, this.seqid());
  var args = new TransactionFileImporter_extract_args();
  args.data = data;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TransactionFileImporterClient.prototype.recv_extract = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TransactionFileImporter_extract_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.col_quantity_error) {
    return callback(result.col_quantity_error);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('extract failed: unknown result');
};
var TransactionFileImporterProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
TransactionFileImporterProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
TransactionFileImporterProcessor.prototype.process_extract = function(seqid, input, output) {
  var args = new TransactionFileImporter_extract_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.extract.length === 1) {
    Q.fcall(this._handler.extract, args.data)
      .then(function(result) {
        var result_obj = new TransactionFileImporter_extract_result({success: result});
        output.writeMessageBegin("extract", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof ttypes.WrongFileStructure) {
          result = new TransactionFileImporter_extract_result(err);
          output.writeMessageBegin("extract", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("extract", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.extract(args.data, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.WrongFileStructure) {
        result_obj = new TransactionFileImporter_extract_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("extract", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("extract", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
