/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package br.com.investtools.radar.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AnalyzerOutputType implements org.apache.thrift.TEnum {
  PIE(0),
  LINE(1);

  private final int value;

  private AnalyzerOutputType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AnalyzerOutputType findByValue(int value) { 
    switch (value) {
      case 0:
        return PIE;
      case 1:
        return LINE;
      default:
        return null;
    }
  }
}
