/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package br.com.investtools.radar.api;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2014-4-8")
public class IndexLinkedBondId implements org.apache.thrift.TBase<IndexLinkedBondId, IndexLinkedBondId._Fields>, java.io.Serializable, Cloneable, Comparable<IndexLinkedBondId> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("IndexLinkedBondId");

  private static final org.apache.thrift.protocol.TField INDEX_FIELD_DESC = new org.apache.thrift.protocol.TField("index", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField FATOR_FIELD_DESC = new org.apache.thrift.protocol.TField("fator", org.apache.thrift.protocol.TType.DOUBLE, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new IndexLinkedBondIdStandardSchemeFactory());
    schemes.put(TupleScheme.class, new IndexLinkedBondIdTupleSchemeFactory());
  }

  public IndexId index; // required
  public double fator; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INDEX((short)1, "index"),
    FATOR((short)2, "fator");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INDEX
          return INDEX;
        case 2: // FATOR
          return FATOR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FATOR_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INDEX, new org.apache.thrift.meta_data.FieldMetaData("index", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, IndexId.class)));
    tmpMap.put(_Fields.FATOR, new org.apache.thrift.meta_data.FieldMetaData("fator", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(IndexLinkedBondId.class, metaDataMap);
  }

  public IndexLinkedBondId() {
  }

  public IndexLinkedBondId(
    IndexId index,
    double fator)
  {
    this();
    this.index = index;
    this.fator = fator;
    setFatorIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public IndexLinkedBondId(IndexLinkedBondId other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetIndex()) {
      this.index = new IndexId(other.index);
    }
    this.fator = other.fator;
  }

  public IndexLinkedBondId deepCopy() {
    return new IndexLinkedBondId(this);
  }

  @Override
  public void clear() {
    this.index = null;
    setFatorIsSet(false);
    this.fator = 0.0;
  }

  public IndexId getIndex() {
    return this.index;
  }

  public IndexLinkedBondId setIndex(IndexId index) {
    this.index = index;
    return this;
  }

  public void unsetIndex() {
    this.index = null;
  }

  /** Returns true if field index is set (has been assigned a value) and false otherwise */
  public boolean isSetIndex() {
    return this.index != null;
  }

  public void setIndexIsSet(boolean value) {
    if (!value) {
      this.index = null;
    }
  }

  public double getFator() {
    return this.fator;
  }

  public IndexLinkedBondId setFator(double fator) {
    this.fator = fator;
    setFatorIsSet(true);
    return this;
  }

  public void unsetFator() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FATOR_ISSET_ID);
  }

  /** Returns true if field fator is set (has been assigned a value) and false otherwise */
  public boolean isSetFator() {
    return EncodingUtils.testBit(__isset_bitfield, __FATOR_ISSET_ID);
  }

  public void setFatorIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FATOR_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INDEX:
      if (value == null) {
        unsetIndex();
      } else {
        setIndex((IndexId)value);
      }
      break;

    case FATOR:
      if (value == null) {
        unsetFator();
      } else {
        setFator((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INDEX:
      return getIndex();

    case FATOR:
      return Double.valueOf(getFator());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INDEX:
      return isSetIndex();
    case FATOR:
      return isSetFator();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof IndexLinkedBondId)
      return this.equals((IndexLinkedBondId)that);
    return false;
  }

  public boolean equals(IndexLinkedBondId that) {
    if (that == null)
      return false;

    boolean this_present_index = true && this.isSetIndex();
    boolean that_present_index = true && that.isSetIndex();
    if (this_present_index || that_present_index) {
      if (!(this_present_index && that_present_index))
        return false;
      if (!this.index.equals(that.index))
        return false;
    }

    boolean this_present_fator = true;
    boolean that_present_fator = true;
    if (this_present_fator || that_present_fator) {
      if (!(this_present_fator && that_present_fator))
        return false;
      if (this.fator != that.fator)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_index = true && (isSetIndex());
    list.add(present_index);
    if (present_index)
      list.add(index);

    boolean present_fator = true;
    list.add(present_fator);
    if (present_fator)
      list.add(fator);

    return list.hashCode();
  }

  @Override
  public int compareTo(IndexLinkedBondId other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIndex()).compareTo(other.isSetIndex());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIndex()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.index, other.index);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFator()).compareTo(other.isSetFator());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFator()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fator, other.fator);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("IndexLinkedBondId(");
    boolean first = true;

    sb.append("index:");
    if (this.index == null) {
      sb.append("null");
    } else {
      sb.append(this.index);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fator:");
    sb.append(this.fator);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (index != null) {
      index.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class IndexLinkedBondIdStandardSchemeFactory implements SchemeFactory {
    public IndexLinkedBondIdStandardScheme getScheme() {
      return new IndexLinkedBondIdStandardScheme();
    }
  }

  private static class IndexLinkedBondIdStandardScheme extends StandardScheme<IndexLinkedBondId> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, IndexLinkedBondId struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INDEX
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.index = new IndexId();
              struct.index.read(iprot);
              struct.setIndexIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FATOR
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.fator = iprot.readDouble();
              struct.setFatorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, IndexLinkedBondId struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.index != null) {
        oprot.writeFieldBegin(INDEX_FIELD_DESC);
        struct.index.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FATOR_FIELD_DESC);
      oprot.writeDouble(struct.fator);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class IndexLinkedBondIdTupleSchemeFactory implements SchemeFactory {
    public IndexLinkedBondIdTupleScheme getScheme() {
      return new IndexLinkedBondIdTupleScheme();
    }
  }

  private static class IndexLinkedBondIdTupleScheme extends TupleScheme<IndexLinkedBondId> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, IndexLinkedBondId struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIndex()) {
        optionals.set(0);
      }
      if (struct.isSetFator()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetIndex()) {
        struct.index.write(oprot);
      }
      if (struct.isSetFator()) {
        oprot.writeDouble(struct.fator);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, IndexLinkedBondId struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.index = new IndexId();
        struct.index.read(iprot);
        struct.setIndexIsSet(true);
      }
      if (incoming.get(1)) {
        struct.fator = iprot.readDouble();
        struct.setFatorIsSet(true);
      }
    }
  }

}

