/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package br.com.investtools.radar.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class SimplePosition extends org.apache.thrift.TUnion<SimplePosition, SimplePosition._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SimplePosition");
  private static final org.apache.thrift.protocol.TField SECURITY_FIELD_DESC = new org.apache.thrift.protocol.TField("security", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField LENDING_FIELD_DESC = new org.apache.thrift.protocol.TField("lending", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField BORROWING_FIELD_DESC = new org.apache.thrift.protocol.TField("borrowing", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SECURITY((short)1, "security"),
    LENDING((short)2, "lending"),
    BORROWING((short)3, "borrowing");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SECURITY
          return SECURITY;
        case 2: // LENDING
          return LENDING;
        case 3: // BORROWING
          return BORROWING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SECURITY, new org.apache.thrift.meta_data.FieldMetaData("security", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Security.class)));
    tmpMap.put(_Fields.LENDING, new org.apache.thrift.meta_data.FieldMetaData("lending", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Lending.class)));
    tmpMap.put(_Fields.BORROWING, new org.apache.thrift.meta_data.FieldMetaData("borrowing", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Borrowing.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SimplePosition.class, metaDataMap);
  }

  public SimplePosition() {
    super();
  }

  public SimplePosition(_Fields setField, java.lang.Object value) {
    super(setField, value);
  }

  public SimplePosition(SimplePosition other) {
    super(other);
  }
  public SimplePosition deepCopy() {
    return new SimplePosition(this);
  }

  public static SimplePosition security(Security value) {
    SimplePosition x = new SimplePosition();
    x.setSecurity(value);
    return x;
  }

  public static SimplePosition lending(Lending value) {
    SimplePosition x = new SimplePosition();
    x.setLending(value);
    return x;
  }

  public static SimplePosition borrowing(Borrowing value) {
    SimplePosition x = new SimplePosition();
    x.setBorrowing(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, java.lang.Object value) throws java.lang.ClassCastException {
    switch (setField) {
      case SECURITY:
        if (value instanceof Security) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type Security for field 'security', but got " + value.getClass().getSimpleName());
      case LENDING:
        if (value instanceof Lending) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type Lending for field 'lending', but got " + value.getClass().getSimpleName());
      case BORROWING:
        if (value instanceof Borrowing) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type Borrowing for field 'borrowing', but got " + value.getClass().getSimpleName());
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected java.lang.Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case SECURITY:
          if (field.type == SECURITY_FIELD_DESC.type) {
            Security security;
            security = new Security();
            security.read(iprot);
            return security;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case LENDING:
          if (field.type == LENDING_FIELD_DESC.type) {
            Lending lending;
            lending = new Lending();
            lending.read(iprot);
            return lending;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case BORROWING:
          if (field.type == BORROWING_FIELD_DESC.type) {
            Borrowing borrowing;
            borrowing = new Borrowing();
            borrowing.read(iprot);
            return borrowing;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case SECURITY:
        Security security = (Security)value_;
        security.write(oprot);
        return;
      case LENDING:
        Lending lending = (Lending)value_;
        lending.write(oprot);
        return;
      case BORROWING:
        Borrowing borrowing = (Borrowing)value_;
        borrowing.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected java.lang.Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case SECURITY:
          Security security;
          security = new Security();
          security.read(iprot);
          return security;
        case LENDING:
          Lending lending;
          lending = new Lending();
          lending.read(iprot);
          return lending;
        case BORROWING:
          Borrowing borrowing;
          borrowing = new Borrowing();
          borrowing.read(iprot);
          return borrowing;
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case SECURITY:
        Security security = (Security)value_;
        security.write(oprot);
        return;
      case LENDING:
        Lending lending = (Lending)value_;
        lending.write(oprot);
        return;
      case BORROWING:
        Borrowing borrowing = (Borrowing)value_;
        borrowing.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case SECURITY:
        return SECURITY_FIELD_DESC;
      case LENDING:
        return LENDING_FIELD_DESC;
      case BORROWING:
        return BORROWING_FIELD_DESC;
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public Security getSecurity() {
    if (getSetField() == _Fields.SECURITY) {
      return (Security)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'security' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setSecurity(Security value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.SECURITY;
    value_ = value;
  }

  public Lending getLending() {
    if (getSetField() == _Fields.LENDING) {
      return (Lending)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'lending' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLending(Lending value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.LENDING;
    value_ = value;
  }

  public Borrowing getBorrowing() {
    if (getSetField() == _Fields.BORROWING) {
      return (Borrowing)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'borrowing' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setBorrowing(Borrowing value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.BORROWING;
    value_ = value;
  }

  public boolean isSetSecurity() {
    return setField_ == _Fields.SECURITY;
  }


  public boolean isSetLending() {
    return setField_ == _Fields.LENDING;
  }


  public boolean isSetBorrowing() {
    return setField_ == _Fields.BORROWING;
  }


  public boolean equals(java.lang.Object other) {
    if (other instanceof SimplePosition) {
      return equals((SimplePosition)other);
    } else {
      return false;
    }
  }

  public boolean equals(SimplePosition other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(SimplePosition other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<java.lang.Object> list = new java.util.ArrayList<java.lang.Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      java.lang.Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
